Verifyta
OnlineTrainingPlatform/Verifiers pull request #2
Opened 2022-10-27 06:48 UTC by frejaz

## Description

*Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.*

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature that assists further development (non-breaking change for the developer)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?
*Please describe the tests that you ran to verify your changes*

### Checklist:

- [ ] You have added a clear title and description for the PR
- [ ] The CI pass
- [ ] There are no merge conflicts
- [ ] The code satisfies the [code standards](https://docs.google.com/document/d/1R9n9MeuRwz3WSrnWZUjrbmGeosTlu1Xz8f5F7gu2AJE/edit#heading=h.e9xl4xfoldow) 
- [ ] I have added docstrings for my code, where needed
- [ ] Code implements intended functionality
- [ ] All relevant tests pass (Black, White, Integration, Monkey, etc.)

2022-11-17 12:17 UTC, Brandhoej commented on .eslintrc
> +    "endOfLine": 0 //0 = off, 1 = warn, 2 = error
Hvorfor er det ændret?

2022-11-17 12:17 UTC, Brandhoej commented on build/index.js
>  "use strict";
/build burde være i .gitignore og .dockerignore

2022-11-17 12:17 UTC, Brandhoej commented on package.json
> +    "memfs": "^3.4.9"
Bliver de her dependencies brugt?

2022-11-17 12:17 UTC, Brandhoej commented on src/infrastructure/currentRequestXml/empty.js
> +// this is empty file, so that this directory is added to build
Kan man ikke bare få den til at lave det directory hvis det mangler?

2022-11-17 12:17 UTC, Brandhoej commented on src/infrastructure/i_cmd_result.ts
> +  verifierOutput: string; // If there is an XML error, this will be an empty string
Kommentaren burde være en docstring

2022-11-17 12:17 UTC, Brandhoej commented on src/infrastructure/i_cmd_result.ts
> +  cmdError?: string;
Hvor kan ``verifierError`` ikke være undefined, men ``cmdError`` kan?

2022-11-17 12:17 UTC, Brandhoej commented on src/infrastructure/paths.spec.ts
> +const SLASH = Os.platform() === 'linux' ? '/' : '\\';
Den bliver ikke brugt?

2022-11-17 12:17 UTC, Brandhoej commented on src/infrastructure/paths.ts
> +const SLASH = Os.platform() === 'linux' ? '/' : '\\';
Den bliver ikke brugt?

2022-11-17 12:17 UTC, Brandhoej commented on src/infrastructure/verifyta_environment.ts
> +  // TODO: input string is not formatted correctly, so file is saved formatting badly...
TODO?

2022-11-17 12:17 UTC, Brandhoej commented on src/infrastructure/verifyta_environment.ts
> +    const seperator = Os.platform() === 'linux' ? '/' : '\\';
Jeg har set det her ret mange steder.

2022-11-17 12:17 UTC, Brandhoej commented on src/infrastructure/verifyta_output_parser.ts
> +  parse(verifytaOuput: ICmdResult, queries: Array<string>): IQueryResult {
Shorthand for array "[]" er bedre.

2022-11-17 12:17 UTC, Brandhoej commented on src/infrastructure/verifyta_verifier.ts
> +    return parsedResult;
``return this.parser.parse(result, queries)``

2022-11-17 12:17 UTC, Brandhoej commented on src/infrastructure/verifyta_verifier.ts
> +    const result = await this.environment.execute(xmlFile);
Ingen fejlhåndtering

2022-11-17 12:17 UTC, Brandhoej commented on src/presentation/verifier_controller.spec.ts
> +describe('/verifier/verifyta', () => {
Der er ingen test som tjekker at resultatet indeholder de korrekte bindings. At skrive ``as xxx`` tjekker ikke for at typen er overholdt for response payload.

2022-11-17 12:17 UTC, Brandhoej commented on src/presentation/verifier_controller.ts
> +        reply.code(404).send('Verifier not found.');
Måske ``Verifier ${verifier} not found``

2022-11-17 12:17 UTC, Brandhoej commented on src/presentation/verifier_controller.ts
> +        await user.verifySolution({
Ingen fejlhåndtering. Det burde given en 500

2022-11-17 12:17 UTC, Brandhoej commented on src/presentation/verifier_controller.ts
> +      reply.send(response);
Hvor bliver status 200 sat?

2022-11-24 10:46 UTC, fatimaosman99 requested changes
Great work. Have few comments :)

2022-11-24 10:46 UTC, fatimaosman99 commented on src/infrastructure/paths.spec.ts
> +});
Add handling Darwin (MacOs paths)

2022-11-24 10:46 UTC, fatimaosman99 commented on src/infrastructure/uppaal_xml_model_builder.ts
> +  }
Add documentation to this.

2022-11-24 10:46 UTC, fatimaosman99 commented on src/infrastructure/uppaal_xml_model_builder.ts
> +  };
This is not used, remove it?

2022-11-24 10:46 UTC, fatimaosman99 commented on src/infrastructure/uppaal_xml_model_builder.ts
> +    // Uses clise to "cut away" the "query" tags in "queries"
```suggestion
    // Uses slice to "cut away" the "query" tags in "queries"
```

2022-11-24 10:46 UTC, fatimaosman99 commented on src/infrastructure/uppaal_xml_model_builder.ts
> +    // Uses clise to "cut away" the "query" tags in "queries"
```suggestion
    // Uses slice to "cut away" the "query" tags in "queries"
```

2022-11-24 10:46 UTC, fatimaosman99 commented on src/infrastructure/verifyta_environment.ts
> +    // Save temerary file
```suggestion
    // Save temporary file
```

2022-11-24 10:46 UTC, fatimaosman99 commented on src/infrastructure/paths.ts
> +}
Add macOs path

2022-11-24 10:46 UTC, fatimaosman99 commented on src/infrastructure/verifyta_environment.ts
> +    const command = `${verifytaPath} -u ${filepath}`;
Add the Mac/darwin path when implemented here

2022-11-24 12:09 UTC, frejaz commented on .eslintrc
> +    "endOfLine": 0 //0 = off, 1 = warn, 2 = error
Fordi det er super annoying + det bliver fikset på hvert save

2022-11-25 12:03 UTC, closed without merging